#!/usr/bin/env python3
"""
build.py — freeze YEETingus into a standalone application.

MUST be run with a Python that Resolve's fusionscript library can be loaded into
(currently 3.6-3.13 — see resolve_bridge.MAX_PY): the frozen app embeds whichever
interpreter builds it.

    Windows:  py -3.13 build.py        ->  dist\\YEETingus.exe
    macOS:    python3.13 build.py      ->  dist/YEETingus.app

No Python is needed on the target machine. yt-dlp is fetched on first run and
ffmpeg is never bundled, so neither is included here — see backend/deps.py for
why that differs by platform.
"""

from __future__ import annotations

import os
import platform
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENTRY = os.path.join(HERE, "backend", "yeet_app.py")

sys.path.insert(0, os.path.join(HERE, "backend"))
import platform_paths as pp  # noqa: E402
from version import APP_NAME as NAME  # noqa: E402

WINDOWS = pp.WINDOWS
MACOS = pp.MACOS

INSTALLER_NAME = f"Install-{NAME}"


def release_asset_name() -> str:
    """Release filename: "<App>-<os>-<arch>", e.g.

        YEETingus-windows-x86_64
        YEETingus-Mac-ARM

    Deliberately carries no version number, so the download link on a website
    stays the same across releases and nothing has to be renamed by hand each
    time. The version is still recoverable from the file itself — the Windows
    version resource and the macOS Info.plist both carry it — and the release
    page states it.
    """
    machine = platform.machine().lower()
    arm = machine in ("arm64", "aarch64")

    if WINDOWS:
        os_tag = "windows"
        arch = "x86_64" if machine in ("amd64", "x86_64") else machine
    elif MACOS:
        os_tag = "Mac"
        arch = "ARM" if arm else "x86_64"
    else:
        os_tag = "linux"
        arch = "aarch64" if arm else ("x86_64" if machine in ("amd64", "x86_64")
                                      else machine)
    return f"{NAME}-{os_tag}-{arch}"


# What PyInstaller leaves in dist/ for us to install. On macOS --windowed
# produces a bundle directory rather than a single file.
APP_ARTIFACT = f"{NAME}.exe" if WINDOWS else (f"{NAME}.app" if MACOS else NAME)

# Reverse-DNS identifier for the macOS bundle. Launch Services keys off this, so
# it must stay stable across releases or every build looks like a new app.
BUNDLE_ID = "com.github.hajdawery.yeetingus"


def _version_tuple(text: str) -> tuple[int, int, int, int]:
    """'1.0.0' -> (1, 0, 0, 0). Windows version resources want four numbers."""
    parts = [int(p) for p in re.findall(r"\d+", text)][:4]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts)  # type: ignore[return-value]


def write_version_resource(exe_name: str, description: str) -> str:
    """Generate a Windows version resource and return its path.

    Without this the exe ships with a blank Properties dialog — no product, no
    version, no copyright. That is both unhelpful to users and a signal that
    heuristic scanners weigh against an unsigned binary, since real software
    carries it. Generated from version.py so it can't drift.
    """
    import version as v

    numbers = _version_tuple(v.__version__)
    out_dir = os.path.join(HERE, "build")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"version_{exe_name}.txt")

    body = f"""# Generated by build.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {v.AUTHOR!r}),
         StringStruct('FileDescription', {description!r}),
         StringStruct('FileVersion', {v.__version__!r}),
         StringStruct('InternalName', {exe_name!r}),
         StringStruct('LegalCopyright', {v.COPYRIGHT!r}),
         StringStruct('OriginalFilename', {exe_name + '.exe'!r}),
         StringStruct('ProductName', {NAME!r}),
         StringStruct('ProductVersion', {v.__version__!r}),
         StringStruct('Comments', {v.AUTHOR_URL!r})])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return path


def make_icns() -> str | None:
    """Build an .icns from assets/logo.png, returning its path.

    macOS won't take the .ico the Windows build uses. sips and iconutil are both
    part of the base system, so this needs nothing installed — which keeps the
    icon a build step rather than a checked-in binary that could drift from the
    logo beside it.

    The source logo is 256x256, so the 512 and 1024 slots a modern bundle would
    like are not generated: upscaling would produce a blurry icon rather than a
    sharp one. Replace assets/logo.png with a 1024x1024 original to get them.
    """
    logo = os.path.join(HERE, "assets", "logo.png")
    if not os.path.isfile(logo):
        return None
    out = os.path.join(HERE, "build", f"{NAME.lower()}.icns")
    iconset = os.path.join(HERE, "build", f"{NAME.lower()}.iconset")
    shutil.rmtree(iconset, ignore_errors=True)
    os.makedirs(iconset, exist_ok=True)

    # (pixel size, filename) — the @2x variants are the same pixels at half the
    # nominal size, which is what Retina asks for.
    wanted = [
        (16, "icon_16x16.png"), (32, "icon_16x16@2x.png"),
        (32, "icon_32x32.png"), (64, "icon_32x32@2x.png"),
        (128, "icon_128x128.png"), (256, "icon_128x128@2x.png"),
        (256, "icon_256x256.png"),
    ]
    try:
        for size, name in wanted:
            subprocess.run(
                ["sips", "-z", str(size), str(size), logo, "--out",
                 os.path.join(iconset, name)],
                check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(["iconutil", "-c", "icns", iconset, "-o", out], check=True)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"(couldn't build .icns: {e} — building without an icon)")
        return None
    finally:
        shutil.rmtree(iconset, ignore_errors=True)
    return out if os.path.isfile(out) else None


def set_bundle_metadata(bundle: str) -> None:
    """Write version and copyright into the bundle's Info.plist.

    PyInstaller has no CLI flag for these, so a bundle otherwise ships as
    version 0.0.0 with no copyright — the macOS equivalent of the blank
    Properties dialog that write_version_resource exists to prevent on Windows,
    and the same signal to anyone deciding whether to trust an unsigned app.

    MUST run before codesign_adhoc: editing Info.plist invalidates any existing
    signature, so signing has to come after this, not before.
    """
    import version as v

    plist = os.path.join(bundle, "Contents", "Info.plist")
    if not os.path.isfile(plist):
        print(f"(no Info.plist at {plist} — skipping metadata)")
        return
    entries = [
        ("CFBundleShortVersionString", v.__version__),
        ("CFBundleVersion", v.__version__),
        ("NSHumanReadableCopyright", v.COPYRIGHT),
    ]
    for key, value in entries:
        # -replace creates the key when absent, so no need to probe first.
        rc = subprocess.run(
            ["plutil", "-replace", key, "-string", value, plist],
            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        if rc.returncode != 0:
            detail = (rc.stderr or b"").decode(errors="replace").strip()
            print(f"(couldn't set {key}: {detail})")
            return
    print(f"Bundle metadata: version {v.__version__}, {v.COPYRIGHT}")


def codesign_adhoc(bundle: str) -> None:
    """Ad-hoc sign the bundle so macOS will run it locally.

    This is NOT notarisation and does not get you past Gatekeeper on someone
    else's machine — a downloaded copy still needs right-click -> Open, or a
    Developer ID certificate and a notarisation pass. What it does buy is a
    valid code signature on the machine that built it, without which recent
    macOS may refuse to launch the bundle at all after PyInstaller rewrites it.
    """
    try:
        subprocess.run(["codesign", "--force", "--deep", "--sign", "-", bundle],
                       check=True, stdout=subprocess.DEVNULL,
                       stderr=subprocess.PIPE)
        print("Ad-hoc signed (local use only — not notarised).")
    except subprocess.CalledProcessError as e:
        detail = (e.stderr or b"").decode(errors="replace").strip()
        print(f"(codesign failed: {detail or e} — the app may not launch)")
    except FileNotFoundError:
        print("(codesign not found — skipping; is Xcode CLT installed?)")


def rust_triple() -> str:
    """The host's Rust target triple, which Tauri expects in a sidecar's name."""
    try:
        out = subprocess.run(["rustc", "-vV"], stdout=subprocess.PIPE, text=True,
                             timeout=30).stdout
        for line in out.splitlines():
            if line.startswith("host:"):
                return line.split(":", 1)[1].strip()
    except (OSError, subprocess.SubprocessError):
        pass
    if WINDOWS:
        return "x86_64-pc-windows-msvc"
    import platform as _platform
    return ("aarch64" if _platform.machine() == "arm64" else "x86_64") + "-apple-darwin"


def build_service() -> int:
    """Freeze backend/service.py as the Tauri app's sidecar.

    The 2.0 app is a Tauri window plus this service. Tauri bundles an
    "external binary" from src-tauri/binaries/<name>-<target triple>[.exe]
    and installs it beside the app exe as <name>[.exe] — which is exactly
    where lib.rs looks for it.

    Console subsystem on purpose: the app reads the port from the service's
    stdout, and a --windowed PyInstaller exe has no stdout. Tauri starts it
    with CREATE_NO_WINDOW, so no console ever shows.
    """
    sys.path.insert(0, os.path.join(HERE, "backend"))
    import resolve_bridge
    if not resolve_bridge.python_is_supported():
        print("ERROR: build the service with a Python the Resolve library loads into: "
              f"{resolve_bridge.version_range_text()}")
        return 1
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        subprocess.run([sys.executable, "-m", "pip", "install", "-U", "pyinstaller"], check=True)

    out_dir = os.path.join(HERE, "app", "src-tauri", "binaries")
    os.makedirs(out_dir, exist_ok=True)
    name = f"yeetingus-service-{rust_triple()}"
    panel = os.path.join(HERE, "premiere", "panel")
    work = os.path.join(HERE, "build", "service")
    shutil.rmtree(work, ignore_errors=True)

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean", "--onefile", "--console",
        "--name", name,
        "--distpath", out_dir,
        "--workpath", work,
        "--specpath", work,
        "--paths", os.path.join(HERE, "backend"),
        "--hidden-import", "engine",
        "--hidden-import", "premiere_bridge",
        "--hidden-import", "resolve_menu",
        "--hidden-import", "config",
        "--hidden-import", "deps",
        "--hidden-import", "media",
        "--hidden-import", "resolve_bridge",
        "--hidden-import", "naming",
        "--hidden-import", "version",
        "--hidden-import", "platform_paths",
        "--exclude-module", "tkinter",
        "--exclude-module", "numpy",
        "--exclude-module", "pytest",
        "--exclude-module", "setuptools",
        # The Premiere panel and the Resolve launcher template ship inside,
        # so Settings can install either.
        "--add-data", f"{panel}{os.pathsep}premiere/panel",
        "--add-data", f"{os.path.join(HERE, 'resolve', NAME + '.lua.in')}{os.pathsep}resolve",
        os.path.join(HERE, "backend", "service.py"),
    ]
    if WINDOWS:
        cmd += ["--version-file", write_version_resource(
            name, f"{NAME} service — the engine behind the {NAME} window")]
        ico = os.path.join(HERE, "assets", f"{NAME.lower()}.ico")
        if os.path.isfile(ico):
            cmd += ["--icon", ico]
    print("Running:", " ".join(cmd))
    rc = subprocess.run(cmd, cwd=HERE).returncode
    if rc != 0:
        return rc
    exe = os.path.join(out_dir, name + (".exe" if WINDOWS else ""))
    if not os.path.isfile(exe):
        print(f"ERROR: build reported success but {exe} is missing.")
        return 1
    print("")
    print(f"Built {exe}  ({os.path.getsize(exe) / 1048576:.1f} MB)")
    print("Next:  cd app && npm run tauri build    (bundles it into the installer)")
    return 0


def main() -> int:
    if "--service" in sys.argv:
        return build_service()

    # The supported range lives in resolve_bridge so there's one place to bump.
    sys.path.insert(0, os.path.join(HERE, "backend"))
    import resolve_bridge

    major, minor = sys.version_info[:2]
    if not resolve_bridge.python_is_supported():
        rng = resolve_bridge.version_range_text()
        newest = "%d.%d" % resolve_bridge.MAX_PY
        print(f"ERROR: building with Python {major}.{minor} would produce an exe that "
              "crashes when it loads Resolve's scripting library.\n"
              f"       Rebuild with {rng}, e.g.:  py -{newest} build.py")
        return 1
    print(f"Building with Python {major}.{minor} (supported range "
          f"{resolve_bridge.version_range_text()}).")

    try:
        import PyInstaller  # noqa: F401  (imported only to test availability)
    except ImportError:
        print("PyInstaller not installed. Installing…")
        subprocess.run([sys.executable, "-m", "pip", "install", "-U", "pyinstaller"],
                       check=True)

    # A stale build/ dir makes PyInstaller reuse old analysis; start clean.
    for d in ("build", "dist"):
        shutil.rmtree(os.path.join(HERE, d), ignore_errors=True)

    # onefile on Windows, onedir on macOS.
    #
    # A .app is a directory by definition, so --onefile can't make it one file;
    # what it actually does is bury a self-extracting binary inside the bundle,
    # which then unpacks to a temp directory on every launch and runs from there.
    # That fights the platform: the signature covers the bundle while the code
    # that actually executes lives somewhere unsigned and transient. PyInstaller
    # calls this out ("clashes with macOS's security") and makes it a hard error
    # in v7.0. onedir is the shape macOS expects, and it starts faster.
    packaging = "--onefile" if WINDOWS else "--onedir"

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        packaging,
        "--windowed",                 # no console window
        "--name", NAME,
        "--paths", os.path.join(HERE, "backend"),
        # imported lazily / by string, so state them explicitly
        "--hidden-import", "config",
        "--hidden-import", "engine",
        "--hidden-import", "deps",
        "--hidden-import", "media",
        "--hidden-import", "theme",
        "--hidden-import", "resolve_bridge",
        "--hidden-import", "naming",
        "--hidden-import", "version",
        "--hidden-import", "platform_paths",
        # trim obvious dead weight
        "--exclude-module", "numpy",
        "--exclude-module", "pytest",
        "--exclude-module", "setuptools",
        ENTRY,
    ]

    # The Windows version resource fills in the exe's Properties dialog; there is
    # no macOS equivalent (the bundle's Info.plist covers it, and PyInstaller
    # writes that from --name and --osx-bundle-identifier).
    if WINDOWS:
        cmd += ["--version-file", write_version_resource(
            NAME, f"{NAME} — media ingestion for DaVinci Resolve")]
    elif MACOS:
        cmd += ["--osx-bundle-identifier", BUNDLE_ID]
        # PyInstaller targets the host architecture by default, so a build made
        # on Apple Silicon runs only on Apple Silicon. Fine for your own machine;
        # not fine for a release asset that says "macOS". --universal produces a
        # universal2 bundle instead, which needs every embedded framework to
        # carry both slices — the python.org builds do, Homebrew's do not.
        if "--universal" in sys.argv:
            cmd += ["--target-arch", "universal2"]
            print("Target: universal2 (Apple Silicon + Intel)")
        else:
            import platform as _platform
            print(f"Target: {_platform.machine()} only "
                  "(pass --universal for a release build)")

    # Icon: used for the app itself, and bundled so the running window/taskbar
    # can set it too (PyInstaller doesn't expose --icon at runtime). The .ico is
    # always added as data since theme.py loads it at runtime on every platform.
    ico = os.path.join(HERE, "assets", f"{NAME.lower()}.ico")
    icon = make_icns() if MACOS else (ico if os.path.isfile(ico) else None)
    if icon:
        cmd += ["--icon", icon]
        print(f"Icon: {icon}")
    else:
        print("(no usable icon — building without one)")
    if os.path.isfile(ico):
        cmd += ["--add-data", f"{ico}{os.pathsep}assets"]

    print("Running:", " ".join(cmd))
    result = subprocess.run(cmd, cwd=HERE)
    if result.returncode != 0:
        return result.returncode

    app = os.path.join(HERE, "dist", APP_ARTIFACT)
    exists = os.path.isdir(app) if MACOS else os.path.isfile(app)
    if not exists:
        print(f"ERROR: build reported success but {app} is missing.")
        return 1

    if MACOS:
        size = sum(os.path.getsize(os.path.join(root, f))
                   for root, _, files in os.walk(app) for f in files
                   if not os.path.islink(os.path.join(root, f))) / 1048576
        # Order matters: the plist edit would invalidate a signature applied
        # before it, so metadata first, then sign.
        set_bundle_metadata(app)
        codesign_adhoc(app)
    else:
        size = os.path.getsize(app) / 1048576
    print(f"\nBuilt {app}  ({size:.1f} MB)")

    install_cmd = "py -3.13 install.py" if WINDOWS else "python3.13 install.py"

    if "--no-installer" in sys.argv:
        print(f"\nNext:  {install_cmd}    (copies it into place + adds the menu entry)")
        return 0

    # macOS gets a staged zip rather than a frozen installer — see
    # build_macos_release for why one cannot be built at all.
    if MACOS:
        asset = build_macos_release(app)
        if not asset:
            return 1
        print(f"\nRelease asset:  {asset}")
        print(f"Next:  {install_cmd}    (or unzip the asset and run install.py there)")
        return 0

    rc = build_installer(app, icon)
    if rc != 0:
        return rc

    sep = "\\" if WINDOWS else "/"
    installer = release_asset_name() + (".exe" if WINDOWS else "")
    print(f"\nRelease asset:  dist{sep}{installer}")
    print(f"Next:  run it to install, or `{install_cmd}` from here.")
    return 0


def build_macos_release(app: str) -> str | None:
    """Stage and zip the macOS release asset. Returns its path.

    There is no macOS counterpart to the Windows one-file installer, for two
    independent reasons:

    * It cannot be built. Freezing install.py with the .app inside it fails —
      PyInstaller cannot nest a signed Python.framework inside its own onefile
      archive, and stops with "bundle format unrecognized, invalid, or
      unsuitable".
    * It would be blocked anyway. An unsigned, un-notarised installer binary is
      exactly what Gatekeeper refuses on download.

    Shipping the bare .app instead is worse than useless: it never creates the
    Resolve menu entry, so the app cannot be launched from Resolve — which is
    the entire point of installing it.

    So the asset is the built bundle staged beside install.py and the modules it
    imports, zipped. The user unzips and runs `python3 install.py`. That needs
    nothing installed: macOS ships Python 3.9, and install.py deliberately
    imports no tkinter and nothing newer than that.

    ditto rather than zip, so the bundle's signature and extended attributes
    survive the round trip.
    """
    print("\n--- macOS release asset ---")
    stage_root = os.path.join(HERE, "build", "macos-release")
    name = release_asset_name()
    stage = os.path.join(stage_root, name)
    shutil.rmtree(stage_root, ignore_errors=True)

    # Mirrors the repo layout, because install.py resolves its resources
    # relative to itself when it isn't frozen.
    payload = [
        (app, os.path.join(stage, "dist", os.path.basename(app))),
        (os.path.join(HERE, "resolve", f"{NAME}.lua.in"),
         os.path.join(stage, "resolve", f"{NAME}.lua.in")),
        (os.path.join(HERE, "resolve", f"launch_{NAME.lower()}.sh"),
         os.path.join(stage, "resolve", f"launch_{NAME.lower()}.sh")),
        (os.path.join(HERE, "backend", "version.py"),
         os.path.join(stage, "backend", "version.py")),
        (os.path.join(HERE, "backend", "platform_paths.py"),
         os.path.join(stage, "backend", "platform_paths.py")),
        (os.path.join(HERE, "install.py"), os.path.join(stage, "install.py")),
    ]
    for src, _ in payload:
        if not os.path.exists(src):
            print(f"ERROR: missing {src}")
            return None

    for src, dst in payload:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        if os.path.isdir(src):
            # ditto, not copytree: preserves the code signature.
            subprocess.run(["ditto", src, dst], check=True)
        else:
            shutil.copy2(src, dst)

    readme = os.path.join(stage, "READ ME FIRST.txt")
    with open(readme, "w", encoding="utf-8") as fh:
        fh.write(_macos_release_readme())

    out = os.path.join(HERE, "dist", f"{name}.zip")
    if os.path.exists(out):
        os.remove(out)
    subprocess.run(["ditto", "-c", "-k", "--keepParent", stage, out], check=True)

    print(f"Built {out}  ({os.path.getsize(out) / 1048576:.1f} MB)")
    return out


def _macos_release_readme() -> str:
    """The note that ships inside the macOS zip.

    Plain text, because it is read in Finder's Quick Look or TextEdit before the
    user has any reason to trust us enough to open anything else.
    """
    import version as v

    return f"""{NAME} {v.__version__} — macOS (Apple Silicon)

INSTALL

  1. Open Terminal and cd into this folder, then run:

         python3 install.py

     macOS already has the Python this needs; nothing to install.

  2. Restart DaVinci Resolve. It caches its Scripts menu at launch, so until
     you restart it will not show the entry.

  3. Find it under:  Workspace -> Scripts -> Utility -> {NAME}

  Do not just copy YEETingus.app somewhere and run it. The installer also
  writes the Resolve menu entry and the launcher shim, and without those
  Resolve has no way to start it.


GATEKEEPER

  This build is ad-hoc signed but NOT notarised, so macOS will refuse to open
  it on the first try. Right-click YEETingus.app and choose Open — that dialog
  has an Open button the one from double-clicking does not. You only do this
  once.

  If you would rather not click through that, build it yourself instead:
  https://github.com/hajdawery/yeetingus


FFMPEG

  {NAME} does not download ffmpeg on macOS, because no Apple Silicon build
  exists whose origin can be vouched for. Install it yourself:

      brew install ffmpeg

  yt-dlp and the JavaScript runtime are fetched automatically on first run —
  both publish official macOS builds.


  {v.COPYRIGHT}  ·  {v.AUTHOR_URL}
"""


def build_installer(app_exe: str, icon: str) -> int:
    """Freeze install.py into a single self-contained installer.

    The app exe, the launch shim and the launcher template are bundled inside it,
    so what ships is one file that needs no Python — the same logic already used
    for dev installs, rather than a second implementation that could drift.
    """
    print("\n--- installer ---")
    shim = os.path.join(HERE, "resolve",
                        f"launch_{NAME.lower()}" + (".bat" if WINDOWS else ".sh"))
    data = [
        (os.path.join(HERE, "resolve", f"{NAME}.lua.in"), "."),
        (os.path.join(HERE, "backend", "version.py"), "."),
        # install.py imports this for the per-OS paths, so it has to travel with
        # it — the installer is frozen without the backend package on sys.path.
        (os.path.join(HERE, "backend", "platform_paths.py"), "."),
        (shim, "."),
    ]
    missing = [src for src, _ in data if not os.path.isfile(src)]
    if missing:
        for m in missing:
            print(f"ERROR: missing {m}")
        return 1

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--onefile",
        "--console",                  # the verification block is the point
        "--name", INSTALLER_NAME,
        "--exclude-module", "tkinter",   # the installer has no UI
        "--exclude-module", "numpy",
        "--exclude-module", "pytest",
        "--exclude-module", "setuptools",
    ]
    if WINDOWS:
        cmd += ["--version-file", write_version_resource(
            INSTALLER_NAME, f"{NAME} installer")]
    for src, dest in data:
        cmd += ["--add-data", f"{src}{os.pathsep}{dest}"]

    # The app itself rides inside the installer, and install.py's resource()
    # looks it up by basename at the bundle root.
    #
    # The destination differs by kind, and getting it wrong is silent: given a
    # directory source, --add-data copies its *contents* into the destination,
    # so "YEETingus.app:." would splatter Contents/ across the bundle root and
    # lose the bundle. Naming the destination reconstitutes the directory.
    app_dest = f"{NAME}.app" if MACOS else "."
    cmd += ["--add-data", f"{app_exe}{os.pathsep}{app_dest}"]

    if icon and os.path.isfile(icon):
        cmd += ["--icon", icon]
    cmd.append(os.path.join(HERE, "install.py"))

    result = subprocess.run(cmd, cwd=HERE)
    if result.returncode != 0:
        return result.returncode

    out = os.path.join(HERE, "dist", INSTALLER_NAME + (".exe" if WINDOWS else ""))
    if not os.path.isfile(out):
        print(f"ERROR: installer build reported success but {out} is missing.")
        return 1

    # Rename to the release convention. PyInstaller has to build under a fixed
    # --name (it is also the internal identifier), so the platform suffix is
    # applied afterwards rather than baked into the build.
    asset = os.path.join(HERE, "dist",
                         release_asset_name() + os.path.splitext(out)[1])
    try:
        if os.path.exists(asset):
            os.remove(asset)
        os.replace(out, asset)
        out = asset
    except OSError as e:
        print(f"! couldn't rename to the release name ({e}); keeping {out}")

    print(f"Built {out}  ({os.path.getsize(out) / 1048576:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
